// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Cadastro_Carro', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Cadastro_Carro', async function() {
    await driver.get("https://cadastrocars.vercel.app/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.linkText("Cadastrar")).click()
    await driver.findElement(By.css(".brandField")).click()
    {
      const dropdown = await driver.findElement(By.css(".brandField"))
      await dropdown.findElement(By.xpath("//option[. = 'Honda']")).click()
    }
    await driver.findElement(By.css(".modelField")).click()
    await driver.findElement(By.css(".modelField")).sendKeys("Honda Model 2")
    await driver.findElement(By.css(".yearField")).click()
    await driver.findElement(By.css(".yearField")).click()
    await driver.findElement(By.css(".yearField")).sendKeys("2024")
    await driver.findElement(By.css(".kmField")).click()
    await driver.findElement(By.css(".kmField")).sendKeys("-10000")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".priceField")).sendKeys("-240000")
    await driver.findElement(By.css(".full")).click()
    await driver.findElement(By.linkText("Cadastrar")).click()
    await driver.findElement(By.css(".brandField")).click()
    {
      const dropdown = await driver.findElement(By.css(".brandField"))
      await dropdown.findElement(By.xpath("//option[. = 'Mercedes-Benz']")).click()
    }
    await driver.findElement(By.css(".modelField")).click()
    await driver.findElement(By.css(".modelField")).sendKeys("Mercedes Type V")
    await driver.findElement(By.css(".yearField")).click()
    await driver.findElement(By.css(".yearField")).sendKeys("0")
    await driver.findElement(By.css(".kmField")).click()
    await driver.findElement(By.css(".kmField")).sendKeys("100000000")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".priceField")).sendKeys("1800000000")
    await driver.findElement(By.css(".full")).click()
  })
})
