// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Editar_Carro', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Editar_Carro', async function() {
    await driver.get("https://cadastrocars.vercel.app/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.css(".carItem:nth-child(1) > .options")).click()
    await driver.findElement(By.css(".carItem:nth-child(1) .pointButton")).click()
    await driver.findElement(By.css(".pointWindowBtn:nth-child(1)")).click()
    await driver.findElement(By.css(".brandField")).click()
    {
      const dropdown = await driver.findElement(By.css(".brandField"))
      await dropdown.findElement(By.xpath("//option[. = 'Volkswagen']")).click()
    }
    await driver.findElement(By.css(".app")).click()
    await driver.findElement(By.css(".modelField")).sendKeys("Volk 3000")
    await driver.findElement(By.css(".app")).click()
    await driver.findElement(By.css(".yearField")).sendKeys("-500000000000000000")
    await driver.findElement(By.css(".form")).click()
    await driver.findElement(By.css(".kmField")).sendKeys("-999999999999999")
    await driver.findElement(By.css(".priceField")).click()
    await driver.findElement(By.css(".priceField")).sendKeys("-9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999")
    await driver.findElement(By.css(".full")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
